name: new release
on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'version bump'
        required: true
        default: 'minor'
        type: choice
        options:
        - minor
        - major
        - patch

jobs:
  build:
    name: new release action
    runs-on: ubuntu-latest
    steps:
      - name: Cancelled
        if: github.ref != 'refs/heads/main'
        run: |
          echo "Can release only from master"
      - uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
      - uses: actions/setup-node@v3
        if: github.ref == 'refs/heads/main'
        with:
          node-version: 16
      - run: yarn install
        if: github.ref == 'refs/heads/main'
      - run: npm install -g standard-version@9.5.0
      - name: Release commit
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b "github-actions-prerelease-$(grep \"version\" package.json | awk -F \" '{print $4}')"
          standard-version --skip.changelog --skip.tag --skip.commit -r ${{ github.event.inputs.version_bump }}
          git add package.json
          git commit -m "Update tag for release to $(grep \"version\" package.json | awk -F \" '{print $4}')"
          git push --set-upstream origin "github-actions-prerelease-$(grep \"version\" package.json | awk -F \" '{print $4}')"
          gh pr create -t "release PR for $(grep \"version\" package.json | awk -F \" '{print $4}')" -b "UPDATE DESCRIPTION. THIS WILL BE USED AS CHANGELOG" -l release-pr
      # - name: Create Release
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     echo "- ${{ github.event.inputs.changelog1 }}" >> LAST_RELEASE.md
      #     echo "- ${{ github.event.inputs.changelog2 }}" >> LAST_RELEASE.md
      #     echo "- ${{ github.event.inputs.changelog3 }}" >> LAST_RELEASE.md
      #     gh release create "$(cat .version)" -F LAST_RELEASE.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
