name: new release
on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'version bump'
        default: 'minor'
        type: choice
        options:
        - minor
        - major
        - patch

jobs:
  create-release-pr:
    uses: ./.github/workflows/new-release-shared.yml
    with:
      VERSION_BUMP: ${{ github.event.inputs.version_bump }}
      PACKAGE_NAME: foo
    secrets: inherit
