name: new release
on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'version bump'
        default: 'minor'
        type: choice
        options:
        - minor
        - major
        - patch

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/new-release-shared.yml
    with:
      VERSION_BUMP: minor
      PACKAGE_NAME: foo
    secrets: inherit
