name: new merge release pr

on:
  pull_request:
    types: [closed]

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release-pr')
    name: new release action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
      - name: create release
        run: |
          gh release create "$(grep \"version\" package.json | awk -F \" '{print $4}')" -t "$(grep \"version\" package.json | awk -F \" '{print $4}')" -n ${{ github.event.pull_request.body }}
