name: new release
on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'version bump'
        required: true
        default: 'minor'
        type: choice
        options:
        - minor
        - major
        - patch

jobs:
  call-workflow:
    uses: ./.github/workflows/new-release-shared.yml
    with:
      VERSION_BUMP: {{ github.event.inputs.version_bump }}
    secrets: inherit
