name: pre-release
on: workflow_dispatch
jobs:
  build:
    name: pre-release action
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Cancelled
        run: |
          echo "Can not pre-release from master"
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
      - name: Done
        run: |
          echo "Done"
