name: pre-release
on: workflow_dispatch
jobs:
  build:
    name: pre-release action
    runs-on: ubuntu-latest
    steps:
      if: github.ref == 'refs/heads/main'
      - name: Cancelled
        run: |
          echo "Can not pre-release from master"
      if: github.ref != 'refs/heads/main'
      - uses: actions/checkout@v1
