name: pre-release
on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'version_bump'
        required: true
        default: 'warning'
        type: choice
        options:
        - minor
        - major

jobs:
  build:
    name: pre-release action
    runs-on: ubuntu-latest
    steps:
      - name: Cancelled
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Can not pre-release from master"

      - uses: actions/checkout@v1
        if: github.ref != 'refs/heads/main'
