name: release
on: workflow_dispatch

jobs:
  build:
    name: release action
    runs-on: ubuntu-latest
    steps:
      - name: Cancelled
        if: github.ref != 'refs/heads/main'
        run: |
          echo "Can release only from master"

      - uses: actions/checkout@v1
        if: github.ref == 'refs/heads/main'
