name: release
on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'version bump'
        required: true
        default: 'warning'
        type: choice
        options:
        - minor
        - major
        - patch
      changelog1:
        description: 'changelog'
        required: true
        type: string
      changelog2:
        description: 'changelog...'
        required: false
        type: string
      changelog3:
        description: 'changelog...'
        required: false
        type: string

jobs:
  build:
    name: release action
    runs-on: ubuntu-latest
    steps:
      - name: Cancelled
        if: github.ref != 'refs/heads/main'
        run: |
          echo "Can release only from master"
      - uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install
      - name: Release commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo -e "\n- ${{ github.event.inputs.changelog3 }}\n\n$(cat CHANGELOG.md)" > CHANGELOG.md
          echo -e "\n- ${{ github.event.inputs.changelog2 }}$(cat CHANGELOG.md)" > CHANGELOG.md
          echo -e "\n- ${{ github.event.inputs.changelog1 }}$(cat CHANGELOG.md)" > CHANGELOG.md
          echo "# $(cat .version)$(cat CHANGELOG.md)" > CHANGELOG.md
          git add .
          git commit -m "doc: update changelog"
          yarn standard-version --skip.changelog
          git push
          git push origin --tags
      - name: Create Release
        run: |
          gh release create "$(cat .version)" --notes "${{ github.event.inputs.changelog1 }}\n${{ github.event.inputs.changelog2 }}\n${{ github.event.inputs.changelog3 }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
