name: release
on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'version_bump'
        required: true
        default: 'warning'
        type: choice
        options:
        - minor
        - major

jobs:
  build:
    name: release action
    runs-on: ubuntu-latest
    steps:
      - name: Cancelled
        if: github.ref != 'refs/heads/main'
        run: |
          echo "Can release only from master"

      - uses: actions/checkout@v1
        if: github.ref == 'refs/heads/main'
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
